export enum actions {
  POPUP_CLOSE = 'POPUP_CLOSE',
  ON_PROGRESS = 'ON_PROGRESS',
  INIT_VENDOR_DATA = 'INIT_VENDOR_DATA',
  INIT_SESSION = 'INIT_SESSION',
  SELECT_VENDOR = 'SELECT_VENDOR',
  FETCH = 'FETCH',
  FETCH_SUCCESS = 'FETCH_SUCCESS',
  AUTHENTICATE = 'AUTHENTICATE',
  AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS',
  POPUP_OPEN = 'POPUP_OPEN',
  INIT = 'INIT',
  ERROR = 'ERROR'
}